### ISSUE TITLE
issue with plugin installed

### ISSUE THREAD

**Issue by deanfields** [charliedevelopment/craft3-element-map#1]
Hi I had this installed, when going to a single page (called home) I got this error, started working when I disabled it.
```
PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR:  column r.sourceid does not exist
LINE 3: LEFT JOIN "elements" "e" ON r.sourceId = e.id
                                    ^
HINT:  Perhaps you meant to reference the column "r.sourceId". in /var/www/html/website/vendor/yiisoft/yii2/db/Command.php:1067
Stack trace:
#0 /var/www/html/website/vendor/yiisoft/yii2/db/Command.php(1067): PDOStatement->execute()
#1 /var/www/html/website/vendor/yiisoft/yii2/db/Command.php(386): yii\db\Command->queryInternal('fetchAll', NULL)
#2 /var/www/html/website/vendor/yiisoft/yii2/db/Query.php(217): yii\db\Command->queryAll()
#3 /var/www/html/website/vendor/craftcms/cms/src/db/Query.php(118): yii\db\Query->all(NULL)
#4 /var/www/html/website/vendor/charliedev/element-map/src/services/Renderer.php(103): craft\db\Query->all()
#5 /var/www/html/website/vendor/charliedev/element-map/src/services/Renderer.php(46): charliedev\elementmap\services\Renderer->getRelationshipGroups(Array, true)
#6 /var/www/html/website/vendor/charliedev/element-map/src/services/Renderer.php(31): charliedev\elementmap\services\Renderer->getElementMap(2)
#7 /var/www/html/website/vendor/charliedev/element-map/src/ElementMap.php(42): charliedev\elementmap\services\Renderer->render(2)
#8 /var/www/html/website/vendor/craftcms/cms/src/web/View.php(1256): charliedev\elementmap\ElementMap->renderEntryElementMap(Array)
#9 /var/www/html/website/storage/runtime/compiled_templates/43/43fb3a34cd97b105801c0bd66efd0fefa129cfa9efd5042a92fdc2265f8d448a.php(609): craft\web\View->invokeHook('cp.entries.edit...', Array)
#10 /var/www/html/website/vendor/twig/twig/lib/Twig/Template.php(188): __TwigTemplate_9703d16510fe02b73863f87a3a0f5fbeda6f77716c926b188c41fbf7d66d0d5a->block_details(Array, Array)
#11 /var/www/html/website/vendor/twig/twig/lib/Twig/Template.php(254): Twig_Template->displayBlock('details', Array, Array, true)
#12 /var/www/html/website/storage/runtime/compiled_templates/ce/ce8a24e55a9c38ab2ea17e74f6c79fed765a8da2a1141da542450ebe7189ea44.php(77): Twig_Template->renderBlock('details', Array, Array)
#13 /var/www/html/website/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_9a3080ad3cdb436e3fd03c91383bcaceb9a21414da897b7f6dc8962940ba1f73->doDisplay(Array, Array)
#14 /var/www/html/website/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#15 /var/www/html/website/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#16 /var/www/html/website/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#17 /var/www/html/website/storage/runtime/compiled_templates/43/43fb3a34cd97b105801c0bd66efd0fefa129cfa9efd5042a92fdc2265f8d448a.php(58): craft\web\twig\Template->display(Array, Array)
#18 /var/www/html/website/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_9703d16510fe02b73863f87a3a0f5fbeda6f77716c926b188c41fbf7d66d0d5a->doDisplay(Array, Array)
#19 /var/www/html/website/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#20 /var/www/html/website/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#21 /var/www/html/website/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#22 /var/www/html/website/vendor/twig/twig/lib/Twig/Template.php(374): craft\web\twig\Template->display(Array)
#23 /var/www/html/website/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#24 /var/www/html/website/vendor/craftcms/cms/src/web/View.php(292): Twig_Environment->render('entries/_edit', Array)
#25 /var/www/html/website/vendor/craftcms/cms/src/web/View.php(340): craft\web\View->renderTemplate('entries/_edit', Array)
#26 /var/www/html/website/vendor/craftcms/cms/src/web/Controller.php(121): craft\web\View->renderPageTemplate('entries/_edit', Array)
#27 /var/www/html/website/vendor/craftcms/cms/src/controllers/EntriesController.php(359): craft\web\Controller->renderTemplate('entries/_edit', Array)
#28 [internal function]: craft\controllers\EntriesController->actionEditEntry('home', 2, NULL, NULL, NULL, Object(craft\elements\Entry))
#29 /var/www/html/website/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#30 /var/www/html/website/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#31 /var/www/html/website/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('edit-entry', Array)
#32 /var/www/html/website/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-entry', Array)
#33 /var/www/html/website/vendor/craftcms/cms/src/web/Application.php(243): yii\base\Module->runAction('entries/edit-en...', Array)
#34 /var/www/html/website/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/edit-en...', Array)
#35 /var/www/html/website/vendor/craftcms/cms/src/web/Application.php(208): yii\web\Application->handleRequest(Object(craft\web\Request))
#36 /var/www/html/website/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#37 /var/www/html/website/web/index.php(21): yii\base\Application->run()
#38 {main}

Next yii\db\Exception: SQLSTATE[42703]: Undefined column: 7 ERROR:  column r.sourceid does not exist
LINE 3: LEFT JOIN "elements" "e" ON r.sourceId = e.id
                                    ^
HINT:  Perhaps you meant to reference the column "r.sourceId".
The SQL being executed was: SELECT "r"."sourceId" AS "id", "e"."type" AS "type"
FROM "relations" "r"
LEFT JOIN "elements" "e" ON r.sourceId = e.id
WHERE ("targetId"=2) AND ((sourceSiteId is null) OR (sourceSiteId = 1)) in /var/www/html/website/vendor/yiisoft/yii2/db/Schema.php:595
Stack trace:
#0 /var/www/html/website/vendor/yiisoft/yii2/db/Command.php(1082): yii\db\Schema->convertException(Object(PDOException), 'SELECT "r"."sou...')
#1 /var/www/html/website/vendor/yiisoft/yii2/db/Command.php(386): yii\db\Command->queryInternal('fetchAll', NULL)
#2 /var/www/html/website/vendor/yiisoft/yii2/db/Query.php(217): yii\db\Command->queryAll()
#3 /var/www/html/website/vendor/craftcms/cms/src/db/Query.php(118): yii\db\Query->all(NULL)
#4 /var/www/html/website/vendor/charliedev/element-map/src/services/Renderer.php(103): craft\db\Query->all()
#5 /var/www/html/website/vendor/charliedev/element-map/src/services/Renderer.php(46): charliedev\elementmap\services\Renderer->getRelationshipGroups(Array, true)
#6 /var/www/html/website/vendor/charliedev/element-map/src/services/Renderer.php(31): charliedev\elementmap\services\Renderer->getElementMap(2)
#7 /var/www/html/website/vendor/charliedev/element-map/src/ElementMap.php(42): charliedev\elementmap\services\Renderer->render(2)
#8 /var/www/html/website/vendor/craftcms/cms/src/web/View.php(1256): charliedev\elementmap\ElementMap->renderEntryElementMap(Array)
#9 /var/www/html/website/storage/runtime/compiled_templates/43/43fb3a34cd97b105801c0bd66efd0fefa129cfa9efd5042a92fdc2265f8d448a.php(609): craft\web\View->invokeHook('cp.entries.edit...', Array)
#10 /var/www/html/website/vendor/twig/twig/lib/Twig/Template.php(188): __TwigTemplate_9703d16510fe02b73863f87a3a0f5fbeda6f77716c926b188c41fbf7d66d0d5a->block_details(Array, Array)
#11 /var/www/html/website/vendor/twig/twig/lib/Twig/Template.php(254): Twig_Template->displayBlock('details', Array, Array, true)
#12 /var/www/html/website/storage/runtime/compiled_templates/ce/ce8a24e55a9c38ab2ea17e74f6c79fed765a8da2a1141da542450ebe7189ea44.php(77): Twig_Template->renderBlock('details', Array, Array)
#13 /var/www/html/website/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_9a3080ad3cdb436e3fd03c91383bcaceb9a21414da897b7f6dc8962940ba1f73->doDisplay(Array, Array)
#14 /var/www/html/website/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#15 /var/www/html/website/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#16 /var/www/html/website/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#17 /var/www/html/website/storage/runtime/compiled_templates/43/43fb3a34cd97b105801c0bd66efd0fefa129cfa9efd5042a92fdc2265f8d448a.php(58): craft\web\twig\Template->display(Array, Array)
#18 /var/www/html/website/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_9703d16510fe02b73863f87a3a0f5fbeda6f77716c926b188c41fbf7d66d0d5a->doDisplay(Array, Array)
#19 /var/www/html/website/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#20 /var/www/html/website/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#21 /var/www/html/website/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#22 /var/www/html/website/vendor/twig/twig/lib/Twig/Template.php(374): craft\web\twig\Template->display(Array)
#23 /var/www/html/website/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#24 /var/www/html/website/vendor/craftcms/cms/src/web/View.php(292): Twig_Environment->render('entries/_edit', Array)
#25 /var/www/html/website/vendor/craftcms/cms/src/web/View.php(340): craft\web\View->renderTemplate('entries/_edit', Array)
#26 /var/www/html/website/vendor/craftcms/cms/src/web/Controller.php(121): craft\web\View->renderPageTemplate('entries/_edit', Array)
#27 /var/www/html/website/vendor/craftcms/cms/src/controllers/EntriesController.php(359): craft\web\Controller->renderTemplate('entries/_edit', Array)
#28 [internal function]: craft\controllers\EntriesController->actionEditEntry('home', 2, NULL, NULL, NULL, Object(craft\elements\Entry))
#29 /var/www/html/website/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#30 /var/www/html/website/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#31 /var/www/html/website/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('edit-entry', Array)
#32 /var/www/html/website/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-entry', Array)
#33 /var/www/html/website/vendor/craftcms/cms/src/web/Application.php(243): yii\base\Module->runAction('entries/edit-en...', Array)
#34 /var/www/html/website/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/edit-en...', Array)
#35 /var/www/html/website/vendor/craftcms/cms/src/web/Application.php(208): yii\web\Application->handleRequest(Object(craft\web\Request))
#36 /var/www/html/website/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#37 /var/www/html/website/web/index.php(21): yii\base\Application->run()
#38 {main}
Additional Information:
Array
(
    [0] => 42703
    [1] => 7
    [2] => ERROR:  column r.sourceid does not exist
LINE 3: LEFT JOIN "elements" "e" ON r.sourceId = e.id
                                    ^
HINT:  Perhaps you meant to reference the column "r.sourceId".
)
```

**Comment by sbossarte** [comment]
@deanfields I've made some corrections to how column names are quoted, which should fix that issue. Please try out the newest version (1.0.1) and let me know if that works. Otherwise I might need some more information from you in order to fix this.

**Comment by deanfields** [comment]
Hey I have just installed this again, and I'm getting the same issue. What info do you need from me to diagnose this?

**Comment by sbossarte** [comment]
Could you please tell me what database you are using, and if possible confirm for me the craft version and plugin version? Just to be sure, the issue still is:

```
PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR: column r.sourceid does not exist
LINE 3: LEFT JOIN "elements" "e" ON r.sourceId = e.id
```

And not with another part of the SQL by chance?

**Comment by deanfields** [comment]
Sure:

App info | version
-------------|------|
PHP version |7.1.11
PostgreSQL|9.6.3
Craft edition & version | Craft Pro 3.0.0-RC4
Yii version | 2.0.13.1

This is the error message:
```
SQLSTATE[42703]: Undefined column: 7 ERROR: column "sourcesiteid" does not exist
LINE 4: WHERE ("targetId"=$1) AND ((sourceSiteId is null) OR (source...
^
HINT: Perhaps you meant to reference the column "r.sourceSiteId".
The SQL being executed was: SELECT "r"."sourceId" AS "id", "e"."type" AS "type"
FROM "relations" "r"
LEFT JOIN "elements" "e" ON "r"."sourceId" = "e"."id"
WHERE ("targetId"=2) AND ((sourceSiteId is null) OR (sourceSiteId = 1))
Error Info: Array
(
    [0] => 42703
    [1] => 7
    [2] => ERROR:  column "sourcesiteid" does not exist
LINE 4: WHERE ("targetId"=$1) AND ((sourceSiteId is null) OR (source...
                                    ^
HINT:  Perhaps you meant to reference the column "r.sourceSiteId".
)
  ```

**Comment by sbossarte** [comment]
Thanks for the info and your patience here. After a little bit of research and asking around, I believe I've got a better understanding of how Yii handles quoting for columns, which PostgreSQL is a bit more strict regarding. This new plugin version (1.0.2) should hopefully fix the issue for you (and anyone else using PostgreSQL).

**Comment by sbossarte** [comment]
Got PosgreSQL working in dev/testing setups here, and was able to confirm that Element Map does work properly now with this database engine.
