### ISSUE TITLE
Bug: Exception when editing a user (Undefined index: site)

### ISSUE THREAD

**Issue by timkelty** [charliedevelopment/craft3-element-map#4]
Not sure if it is relevant, but this is on a multi-site.

```yii\base\ErrorException: Undefined index: site in /app/vendor/composer/charliedev/element-map/src/ElementMap.php:65
Stack trace:
#0 /app/vendor/composer/craftcms/cms/src/web/View.php(1237): charliedev\elementmap\ElementMap->renderUserElementMap()
#1 /app/storage/runtime/compiled_templates/f0/f00b4e361427aa5c7fe3c646ff2dbb0cda7d919665a76f9ca2f332dc331922e6.php(712): craft\web\View->invokeHook()
#2 /app/vendor/composer/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_b2e78235238465d5ea6955a958e0fced7b7791d65aeeb51f81a0307b140b4681->block_details()
#3 /app/vendor/composer/twig/twig/lib/Twig/Template.php(255): __TwigTemplate_419c441f428cbf41f9307925f8240dc882a6c54364d6e752664c4074c901238a->displayBlock()
#4 /app/storage/runtime/compiled_templates/32/32351c1a2c663312a4c07e486d75fb35e0c173d3c909e4a1784ee2b33a646441.php(81): __TwigTemplate_419c441f428cbf41f9307925f8240dc882a6c54364d6e752664c4074c901238a->renderBlock()
#5 /app/vendor/composer/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_419c441f428cbf41f9307925f8240dc882a6c54364d6e752664c4074c901238a->doDisplay()
#6 /app/vendor/composer/craftcms/cms/src/web/twig/Template.php(49): __TwigTemplate_419c441f428cbf41f9307925f8240dc882a6c54364d6e752664c4074c901238a->displayWithErrorHandling()
#7 /app/vendor/composer/twig/twig/lib/Twig/Template.php(367): __TwigTemplate_419c441f428cbf41f9307925f8240dc882a6c54364d6e752664c4074c901238a->displayWithErrorHandling()
#8 /app/vendor/composer/craftcms/cms/src/web/twig/Template.php(31): __TwigTemplate_419c441f428cbf41f9307925f8240dc882a6c54364d6e752664c4074c901238a->display()
#9 /app/storage/runtime/compiled_templates/f0/f00b4e361427aa5c7fe3c646ff2dbb0cda7d919665a76f9ca2f332dc331922e6.php(86): __TwigTemplate_419c441f428cbf41f9307925f8240dc882a6c54364d6e752664c4074c901238a->display()
#10 /app/vendor/composer/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_b2e78235238465d5ea6955a958e0fced7b7791d65aeeb51f81a0307b140b4681->doDisplay()
#11 /app/vendor/composer/craftcms/cms/src/web/twig/Template.php(49): __TwigTemplate_b2e78235238465d5ea6955a958e0fced7b7791d65aeeb51f81a0307b140b4681->displayWithErrorHandling()
#12 /app/vendor/composer/twig/twig/lib/Twig/Template.php(367): __TwigTemplate_b2e78235238465d5ea6955a958e0fced7b7791d65aeeb51f81a0307b140b4681->displayWithErrorHandling()
#13 /app/vendor/composer/craftcms/cms/src/web/twig/Template.php(31): __TwigTemplate_b2e78235238465d5ea6955a958e0fced7b7791d65aeeb51f81a0307b140b4681->display()
#14 /app/vendor/composer/twig/twig/lib/Twig/Template.php(375): __TwigTemplate_b2e78235238465d5ea6955a958e0fced7b7791d65aeeb51f81a0307b140b4681->display()
#15 /app/vendor/composer/twig/twig/lib/Twig/Environment.php(289): __TwigTemplate_b2e78235238465d5ea6955a958e0fced7b7791d65aeeb51f81a0307b140b4681->render()
#16 /app/vendor/composer/craftcms/cms/src/web/View.php(330): craft\web\twig\Environment->render()
#17 /app/vendor/composer/craftcms/cms/src/web/View.php(377): craft\web\View->renderTemplate()
#18 /app/vendor/composer/craftcms/cms/src/web/Controller.php(155): craft\web\View->renderPageTemplate()
#19 /app/vendor/composer/craftcms/cms/src/controllers/UsersController.php(853): craft\controllers\UsersController->renderTemplate()
#20 /app/vendor/composer/yiisoft/yii2/base/InlineAction.php(57): craft\controllers\UsersController->actionEditUser()
#21 /app/vendor/composer/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/app/vendor/composer/yiisoft/yii2/base/InlineAction.php:57}()
#22 /app/vendor/composer/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#23 /app/vendor/composer/craftcms/cms/src/web/Controller.php(103): craft\controllers\UsersController->runAction()
#24 /app/vendor/composer/yiisoft/yii2/base/Module.php(528): craft\controllers\UsersController->runAction()
#25 /app/vendor/composer/craftcms/cms/src/web/Application.php(282): craft\web\Application->runAction()
#26 /app/vendor/composer/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#27 /app/vendor/composer/craftcms/cms/src/web/Application.php(271): craft\web\Application->handleRequest()
#28 /app/vendor/composer/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#29 /app/vendor/composer/fusionary/craftcms-bootstrap/src/Bootstrap.php(76): craft\web\Application->run()
#30 /app/public/index.php(3): fusionary\craftcms\bootstrap\Bootstrap::run()
#31 {main}```

**Comment by sbossarte** [comment]
Turns out, users don't get a site when their settings are rendered, they're always associated with the primary site instead.

Thanks for the report, this is now fixed in 1.1.1
